project_id = "xrbvyfoewbwywrwocrpf"

[functions.create-admin]
verify_jwt = true

[functions.list-admins]
verify_jwt = true

[functions.lookup-user]
verify_jwt = true

[functions.lookup-rma]
verify_jwt = false

[functions.submit-shipping]
verify_jwt = false
