project_id = "xrbvyfoewbwywrwocrpf"


[functions.list-admins]
verify_jwt = true

[functions.lookup-user]
verify_jwt = true

[functions.lookup-rma]
verify_jwt = false

[functions.submit-shipping]
verify_jwt = false

[functions.submit-outbound-shipping]
verify_jwt = true

[functions.log-login]
verify_jwt = false

[functions.submit-rma]
verify_jwt = false

[functions.rma-ai-analysis]
verify_jwt = true

[functions.generate-rma-embeddings]
verify_jwt = true

[functions.import-rma-csv]
verify_jwt = true

[functions.slack-notify]
verify_jwt = false

[functions.update-rma-status]
verify_jwt = false

[functions.generate-email-embeddings]
verify_jwt = false

[functions.kickoff-email-embedding-job]
verify_jwt = false

[functions.email-knowledge-chat]
verify_jwt = true

[functions.update-ai-settings]
verify_jwt = true

[functions.upload-knowledge-file]
verify_jwt = true

[functions.draft-email-reply]
verify_jwt = true

[functions.generate-knowledge-question]
verify_jwt = true

[functions.generate-practice-email]
verify_jwt = true

[functions.gmail-list-messages]
verify_jwt = true

[functions.gmail-get-message]
verify_jwt = true

[functions.gmail-modify-message]
verify_jwt = true

[functions.send-shipping-reminders]
verify_jwt = false


[functions.process-email-queue]
verify_jwt = true

[functions.send-transactional-email]
verify_jwt = false

[functions.preview-transactional-email]
verify_jwt = false

[functions.handle-email-unsubscribe]
verify_jwt = false

[functions.handle-email-suppression]
verify_jwt = false

[functions.send-rma-reply]
verify_jwt = true

[functions.lookup-rma-reply-thread]
verify_jwt = false

[functions.submit-customer-reply]
verify_jwt = false

[functions.shopify-find-orders-by-email]
verify_jwt = true

