project_id = "xrbvyfoewbwywrwocrpf"

[functions.create-admin]
verify_jwt = true

[functions.list-admins]
verify_jwt = true

[functions.lookup-user]
verify_jwt = true

[functions.lookup-rma]
verify_jwt = false

[functions.submit-shipping]
verify_jwt = false

[functions.submit-outbound-shipping]
verify_jwt = true

[functions.log-login]
verify_jwt = false

[functions.submit-rma]
verify_jwt = false

[functions.rma-ai-analysis]
verify_jwt = true

[functions.generate-rma-embeddings]
verify_jwt = true

[functions.import-rma-csv]
verify_jwt = true

[functions.slack-notify]
verify_jwt = false

[functions.update-rma-status]
verify_jwt = false

[functions.generate-email-embeddings]
verify_jwt = false

[functions.kickoff-email-embedding-job]
verify_jwt = false

[functions.email-knowledge-chat]
verify_jwt = true

[functions.update-ai-settings]
verify_jwt = true

[functions.upload-knowledge-file]
verify_jwt = true

[functions.draft-email-reply]
verify_jwt = true
