import { useState, useRef } from "react";
import { Upload, Check, Loader2, X, Image as ImageIcon } from "lucide-react";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { useNavigate } from "react-router-dom";

const customerTypes = [
  { id: "consumer", label: "一般消費者" },
  { id: "dealer", label: "經銷商" },
  { id: "agent", label: "代理商" },
  { id: "dealer-agent", label: "經銷/代理商多筆" },
];

const issueTypes = [
  "螢幕問題",
  "電池問題",
  "充電問題",
  "按鍵問題",
  "軟體問題",
  "外觀損壞",
  "其他",
];

const accessories = [
  { id: "complete", label: "完整包裝" },
  { id: "box", label: "外包裝盒" },
  { id: "charger", label: "充電組" },
  { id: "warranty", label: "保固卡" },
  { id: "strap", label: "錶帶" },
  { id: "other", label: "其他" },
  { id: "none", label: "無" },
];

const RmaForm = () => {
  const navigate = useNavigate();
  const fileInputRef = useRef<HTMLInputElement>(null);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [customerType, setCustomerType] = useState("consumer");
  const [selectedAccessories, setSelectedAccessories] = useState<string[]>([]);
  const [agreed, setAgreed] = useState(false);
  const [dragActive, setDragActive] = useState(false);
  const [uploadedFiles, setUploadedFiles] = useState<File[]>([]);

  // Form fields
  const [customerName, setCustomerName] = useState("");
  const [customerEmail, setCustomerEmail] = useState("");
  const [customerPhone, setCustomerPhone] = useState("");
  const [serialNumber, setSerialNumber] = useState("");
  const [customerAddress, setCustomerAddress] = useState("");
  const [productModel, setProductModel] = useState("");
  const [issueType, setIssueType] = useState("");
  const [purchaseDate, setPurchaseDate] = useState("");
  const [issueDescription, setIssueDescription] = useState("");

  const handleAccessoryToggle = (id: string) => {
    setSelectedAccessories((prev) =>
      prev.includes(id) ? prev.filter((a) => a !== id) : [...prev, id]
    );
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    
    if (!agreed) {
      toast.error("請先同意服務條款和隱私政策");
      return;
    }

    // Validate required fields
    if (!customerName.trim()) {
      toast.error("請輸入客戶姓名");
      return;
    }
    if (!customerEmail.trim()) {
      toast.error("請輸入電子郵件");
      return;
    }
    if (!customerPhone.trim()) {
      toast.error("請輸入客戶電話");
      return;
    }
    if (!issueType) {
      toast.error("請選擇故障問題");
      return;
    }
    if (!issueDescription.trim()) {
      toast.error("請描述問題");
      return;
    }

    setIsSubmitting(true);

    try {
      // Build product name from customer type and model
      const customerTypeLabel = customerTypes.find(t => t.id === customerType)?.label || customerType;
      const productName = productModel.trim() || "未指定型號";

      // Upload photos to storage
      const photoUrls: string[] = [];
      for (const file of uploadedFiles) {
        const fileExt = file.name.split('.').pop();
        const fileName = `${Date.now()}-${Math.random().toString(36).substring(2)}.${fileExt}`;
        const filePath = `rma-photos/${fileName}`;
        
        const { error: uploadError } = await supabase.storage
          .from('rma-photos')
          .upload(fileName, file);
        
        if (!uploadError) {
          const { data: urlData } = supabase.storage
            .from('rma-photos')
            .getPublicUrl(fileName);
          
          if (urlData?.publicUrl) {
            photoUrls.push(urlData.publicUrl);
          }
        }
      }

      const { data, error } = await supabase
        .from("rma_requests")
        .insert([{
          rma_number: "", // Auto-generated by database trigger
          customer_name: customerName.trim(),
          customer_email: customerEmail.trim(),
          customer_phone: customerPhone.trim(),
          customer_address: customerAddress.trim() || null,
          product_name: productName,
          product_model: productModel.trim() || null,
          serial_number: serialNumber.trim() || null,
          issue_type: issueType,
          issue_description: `[${customerTypeLabel}] ${issueDescription.trim()}${selectedAccessories.length > 0 ? `\n\n隨附物品: ${selectedAccessories.map(id => accessories.find(a => a.id === id)?.label).join(", ")}` : ""}`,
          purchase_date: purchaseDate || null,
          photo_urls: photoUrls.length > 0 ? photoUrls : null,
        }])
        .select("rma_number")
        .single();

      if (error) throw error;

      // Navigate to confirmation page with the RMA number
      navigate(`/rma-confirmation?rma=${data.rma_number}`);
    } catch (error: any) {
      console.error("Error submitting RMA:", error);
      toast.error("提交失敗，請稍後再試");
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleDrag = (e: React.DragEvent) => {
    e.preventDefault();
    e.stopPropagation();
    if (e.type === "dragenter" || e.type === "dragover") {
      setDragActive(true);
    } else if (e.type === "dragleave") {
      setDragActive(false);
    }
  };

  const handleDrop = (e: React.DragEvent) => {
    e.preventDefault();
    e.stopPropagation();
    setDragActive(false);
    
    const files = Array.from(e.dataTransfer.files);
    handleFiles(files);
  };

  const handleFileInput = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files) {
      const files = Array.from(e.target.files);
      handleFiles(files);
    }
  };

  const handleFiles = (files: File[]) => {
    const validFiles = files.filter(file => {
      // Check file type
      if (!file.type.startsWith("image/")) {
        toast.error(`${file.name} 不是有效的圖片格式`);
        return false;
      }
      // Check file size (10MB limit)
      if (file.size > 10 * 1024 * 1024) {
        toast.error(`${file.name} 超過 10MB 限制`);
        return false;
      }
      return true;
    });

    if (validFiles.length > 0) {
      setUploadedFiles(prev => [...prev, ...validFiles].slice(0, 5)); // Max 5 files
      if (uploadedFiles.length + validFiles.length > 5) {
        toast.info("最多只能上傳 5 張照片");
      }
    }
  };

  const removeFile = (index: number) => {
    setUploadedFiles(prev => prev.filter((_, i) => i !== index));
  };

  const handleUploadClick = () => {
    fileInputRef.current?.click();
  };

  return (
    <form onSubmit={handleSubmit} className="rma-card animate-fade-in">
      <div className="mb-6">
        <h2 className="text-xl font-bold text-foreground">建立新的 RMA</h2>
        <p className="text-sm text-muted-foreground mt-1">
          請填寫以下資訊以建立維修申請
        </p>
      </div>

      {/* Customer Type */}
      <div className="mb-6">
        <label className="rma-label">寄件人身分</label>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
          {customerTypes.map((type) => (
            <label
              key={type.id}
              className="flex items-center gap-2 cursor-pointer"
            >
              <input
                type="radio"
                name="customerType"
                value={type.id}
                checked={customerType === type.id}
                onChange={(e) => setCustomerType(e.target.value)}
                className="w-4 h-4 text-primary border-border focus:ring-primary"
              />
              <span className="text-sm text-foreground">{type.label}</span>
            </label>
          ))}
        </div>
      </div>

      {/* Customer Info */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-4">
        <div>
          <label className="rma-label">客戶姓名 *</label>
          <input
            type="text"
            placeholder="請輸入客戶姓名"
            className="rma-input"
            value={customerName}
            onChange={(e) => setCustomerName(e.target.value)}
            required
          />
        </div>
        <div>
          <label className="rma-label">電子郵件 *</label>
          <input
            type="email"
            placeholder="請輸入電子郵件"
            className="rma-input"
            value={customerEmail}
            onChange={(e) => setCustomerEmail(e.target.value)}
            required
          />
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-4">
        <div>
          <label className="rma-label">客戶電話 *</label>
          <input
            type="tel"
            placeholder="請輸入客戶電話"
            className="rma-input"
            value={customerPhone}
            onChange={(e) => setCustomerPhone(e.target.value)}
            required
          />
        </div>
        <div>
          <label className="rma-label">產品序號</label>
          <input
            type="text"
            placeholder="請輸入產品序號"
            className="rma-input"
            value={serialNumber}
            onChange={(e) => setSerialNumber(e.target.value)}
          />
        </div>
      </div>

      <div className="mb-4">
        <label className="rma-label">客戶地址</label>
        <textarea
          placeholder="請輸入客戶地址"
          className="rma-input min-h-[80px] resize-none"
          value={customerAddress}
          onChange={(e) => setCustomerAddress(e.target.value)}
        />
      </div>

      {/* Product Info */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-4">
        <div>
          <label className="rma-label">產品型號</label>
          <input
            type="text"
            placeholder="請輸入產品型號"
            className="rma-input"
            value={productModel}
            onChange={(e) => setProductModel(e.target.value)}
          />
        </div>
        <div>
          <label className="rma-label">故障問題 *</label>
          <select 
            className="rma-input"
            value={issueType}
            onChange={(e) => setIssueType(e.target.value)}
            required
          >
            <option value="">選擇故障問題</option>
            {issueTypes.map((issue) => (
              <option key={issue} value={issue}>
                {issue}
              </option>
            ))}
          </select>
        </div>
      </div>

      <div className="mb-4">
        <label className="rma-label">購買日期</label>
        <input 
          type="date" 
          className="rma-input"
          value={purchaseDate}
          onChange={(e) => setPurchaseDate(e.target.value)}
        />
      </div>

      <div className="mb-4">
        <label className="rma-label">問題描述 *</label>
        <textarea
          placeholder="請詳細描述問題..."
          className="rma-input min-h-[120px] resize-none"
          value={issueDescription}
          onChange={(e) => setIssueDescription(e.target.value)}
          required
        />
      </div>

      {/* Photo Upload */}
      <div className="mb-6">
        <label className="rma-label">產品照片</label>
        <input
          type="file"
          ref={fileInputRef}
          onChange={handleFileInput}
          accept="image/*"
          multiple
          className="hidden"
        />
        <div
          className={`border-2 border-dashed rounded-lg p-8 text-center transition-colors cursor-pointer ${
            dragActive
              ? "border-primary bg-accent"
              : "border-border hover:border-primary/50"
          }`}
          onDragEnter={handleDrag}
          onDragLeave={handleDrag}
          onDragOver={handleDrag}
          onDrop={handleDrop}
          onClick={handleUploadClick}
        >
          <Upload className="w-8 h-8 mx-auto mb-2 text-muted-foreground" />
          <p className="text-sm text-muted-foreground">
            <span className="text-primary font-medium hover:underline">
              點擊上傳照片
            </span>{" "}
            或拖放到此處
          </p>
          <p className="text-xs text-muted-foreground mt-1">
            PNG, JPG, GIF 最大 10MB，最多 5 張
          </p>
        </div>

        {/* Uploaded Files Preview */}
        {uploadedFiles.length > 0 && (
          <div className="mt-4 grid grid-cols-2 sm:grid-cols-3 md:grid-cols-5 gap-3">
            {uploadedFiles.map((file, index) => (
              <div key={index} className="relative group">
                <div className="aspect-square rounded-lg border border-border overflow-hidden bg-muted">
                  <img
                    src={URL.createObjectURL(file)}
                    alt={file.name}
                    className="w-full h-full object-cover"
                  />
                </div>
                <button
                  type="button"
                  onClick={(e) => {
                    e.stopPropagation();
                    removeFile(index);
                  }}
                  className="absolute -top-2 -right-2 w-6 h-6 bg-destructive text-destructive-foreground rounded-full flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity"
                >
                  <X className="w-4 h-4" />
                </button>
                <p className="text-xs text-muted-foreground mt-1 truncate">
                  {file.name}
                </p>
              </div>
            ))}
          </div>
        )}
      </div>

      {/* Accessories */}
      <div className="mb-6">
        <label className="rma-label">隨附寄出物品</label>
        <div className="space-y-2">
          {accessories.map((acc) => (
            <label
              key={acc.id}
              className="flex items-center gap-2 cursor-pointer"
            >
              <div
                className={`w-5 h-5 rounded border flex items-center justify-center transition-colors ${
                  selectedAccessories.includes(acc.id)
                    ? "bg-primary border-primary"
                    : "border-border bg-card"
                }`}
                onClick={() => handleAccessoryToggle(acc.id)}
              >
                {selectedAccessories.includes(acc.id) && (
                  <Check className="w-3 h-3 text-primary-foreground" />
                )}
              </div>
              <span className="text-sm text-foreground">{acc.label}</span>
            </label>
          ))}
        </div>
      </div>

      {/* Agreement */}
      <div className="mb-6">
        <label className="flex items-center gap-2 cursor-pointer">
          <div
            className={`w-5 h-5 rounded border flex items-center justify-center transition-colors ${
              agreed ? "bg-primary border-primary" : "border-border bg-card"
            }`}
            onClick={() => setAgreed(!agreed)}
          >
            {agreed && <Check className="w-3 h-3 text-primary-foreground" />}
          </div>
          <span className="text-sm text-foreground">
            我同意服務條款和隱私政策 *
          </span>
        </label>
      </div>

      {/* Submit */}
      <button 
        type="submit" 
        className="w-full rma-btn-primary py-4 text-base disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2"
        disabled={isSubmitting}
      >
        {isSubmitting ? (
          <>
            <Loader2 className="w-5 h-5 animate-spin" />
            提交中...
          </>
        ) : (
          "建立RMA"
        )}
      </button>
    </form>
  );
};

export default RmaForm;
