import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
};

interface RmaSubmission {
  customer_name: string;
  customer_email: string;
  customer_phone: string;
  customer_address?: string;
  product_name: string;
  product_model?: string;
  serial_number?: string;
  issue_type: string;
  issue_description: string;
  purchase_date?: string;
  photo_urls?: string[];
  customer_type?: string;
}

interface MultiRmaRequest {
  products: RmaSubmission[];
}

serve(async (req) => {
  // Handle CORS preflight requests
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const supabaseServiceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;

    // Use service role to bypass RLS
    const supabase = createClient(supabaseUrl, supabaseServiceKey);

    const body = await req.json();
    console.log("Received submit-rma request:", JSON.stringify(body));

    // Check if this is a multi-product submission
    const isMulti = Array.isArray(body.products);
    const products: RmaSubmission[] = isMulti ? body.products : [body];

    // Validate required fields for each product
    for (const product of products) {
      if (!product.customer_name?.trim()) {
        return new Response(
          JSON.stringify({ error: "客戶姓名為必填" }),
          { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }
      if (!product.customer_email?.trim()) {
        return new Response(
          JSON.stringify({ error: "電子郵件為必填" }),
          { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }
      if (!product.customer_phone?.trim()) {
        return new Response(
          JSON.stringify({ error: "客戶電話為必填" }),
          { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }
      if (!product.issue_type?.trim()) {
        return new Response(
          JSON.stringify({ error: "故障問題為必填" }),
          { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }
      if (!product.issue_description?.trim()) {
        return new Response(
          JSON.stringify({ error: "問題描述為必填" }),
          { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }
    }

    const results: { rma_number: string; product_model?: string; serial_number?: string }[] = [];

    // Insert each product
    for (const product of products) {
      const insertData = {
        rma_number: "", // Will be auto-generated by trigger
        customer_name: product.customer_name.trim(),
        customer_email: product.customer_email.trim(),
        customer_phone: product.customer_phone.trim(),
        customer_address: product.customer_address?.trim() || null,
        product_name: product.product_name || "未指定型號",
        product_model: product.product_model?.trim() || null,
        serial_number: product.serial_number?.trim() || null,
        issue_type: product.issue_type,
        issue_description: product.issue_description,
        purchase_date: product.purchase_date || null,
        photo_urls: product.photo_urls?.length ? product.photo_urls : null,
        customer_type: product.customer_type || null,
      };

      console.log("Inserting RMA:", JSON.stringify(insertData));

      const { data, error } = await supabase
        .from("rma_requests")
        .insert([insertData])
        .select("rma_number")
        .single();

      if (error) {
        console.error("Error inserting RMA:", error);
        return new Response(
          JSON.stringify({ error: `提交失敗: ${error.message}` }),
          { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }

      results.push({
        rma_number: data.rma_number,
        product_model: product.product_model,
        serial_number: product.serial_number,
      });

      console.log("Successfully created RMA:", data.rma_number);
    }

    // Return appropriate response
    if (isMulti) {
      return new Response(
        JSON.stringify({ results }),
        { headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    } else {
      return new Response(
        JSON.stringify({ rma_number: results[0].rma_number }),
        { headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }
  } catch (error: unknown) {
    console.error("Error in submit-rma function:", error);
    const errorMessage = error instanceof Error ? error.message : "Internal server error";
    return new Response(
      JSON.stringify({ error: errorMessage }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
